name: Update PDF Index
on:
  push:
    paths:
      - 'notes/**'
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Hourly updates

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get file metadata
        
      - name: Find PDFs
        id: find-pdfs
        run: |
          echo "Checking notes directory..."
          ls -la notes/
          
          # Count PDF files
          PDF_COUNT=$(find notes -type f -name '*.pdf' | wc -l)
          echo "Found $PDF_COUNT PDF files"
          
          # Set output for next steps
          echo "pdf_count=$PDF_COUNT" >> $GITHUB_OUTPUT
          
      - name: Generate JSON
        if: steps.find-pdfs.outputs.pdf_count != '0'
        run: |
          echo 'const fs = require("fs");
          const path = require("path");
          
          const pdfs = fs.readdirSync("notes")
            .filter(f => f.toLowerCase().endsWith(".pdf"))
            .map(f => {
              const stat = fs.statSync(path.join("notes", f));
              return {
                name: f,
                size: formatBytes(stat.size),
                date: stat.mtime.toISOString().split("T")[0]
              };
            });
          
          fs.writeFileSync("pdf-list.json", JSON.stringify(pdfs, null, 2));
          
          function formatBytes(bytes) {
            const units = ["B", "KB", "MB", "GB"];
            if (bytes === 0) return "0 B";
            const i = Math.floor(Math.log(bytes) / Math.log(1024));
            return `${(bytes / Math.pow(1024, i)).toFixed(1)} ${units[i]}`;
          }' > generate.js
          
          node generate.js
          cat pdf-list.json
          
      - name: Create empty JSON if no PDFs
        if: steps.find-pdfs.outputs.pdf_count == '0'
        run: |
          echo '[]' > pdf-list.json
          echo "Created empty PDF list"
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add pdf-list.json
          git diff --cached --quiet || git commit -m "Update PDF list"
          git push